### ISSUE TITLE
Implement auto annotations

### ISSUE THREAD

**Issue by hasangokce** [HBilge/Dolphin#50]
Issue type: `task`
Sub issues: #62 #63 #64 

Related documents on the Wiki:

- [4.1.4. Annotations shall be presented in JSON-LD (JSON Linked Data) format.](https://github.com/HBilge/Dolphin/wiki/Software-Requirements-Specification-(SRS)-Document)
- [4.2.2. System shall use UMLS for annotations.](https://github.com/HBilge/Dolphin/wiki/Software-Requirements-Specification-(SRS)-Document)
- [Use case](https://github.com/HBilge/Dolphin/wiki/Use-Case-Diagram)
- [Class diagram](https://github.com/HBilge/Dolphin/wiki/Class-Diagram)
- [Sequence diagram](https://github.com/HBilge/Dolphin/wiki/Sequence-Diagram)

***

We have three main collections on the database. We'll populate the annotations collection by using articles and ontologies.
1. articles ~84 463 entries
2. ontologies ~2 268 entries
3. **annotations**

* **Problem:** Approximate search operation: 84463 * 2268 = ~200 million. If each search query takes 1 second, the process takes 235 days!
* **Solution:** There is no solution for now. One possible solution might be: ... ?

*** 

## Source:
* https://json-ld.org/
* http://webannotation.org/
* https://www.youtube.com/watch?v=kZ77X67GUfk&ab_channel=MongoDB
* https://www.slideshare.net/gkellogg1/jsonld-and-mongodb
* http://www.markus-lanthaler.com/research/creating-3rd-generation-web-apis-with-hydra.pdf
* https://towardsdatascience.com/searching-and-replacing-text-db983d19a184
* https://www.djongomapper.com/get-started/
* https://stackabuse.com/replace-occurrences-of-a-substring-in-string-with-python/
* https://blog.etianen.com/blog/2013/06/08/django-querysets/

## Tasks
- [ ] create different database for annotations
- [ ] check if article has abstract
- [ ] use regex to be accure, e.g. **organ**ization

**Comment by hasangokce** [comment]
```mermaid
sequenceDiagram
    participant Annotator
    participant DB_articles_article
    participant DB_ontologies_ontology
    participant Annotation
    Annotator->>DB_articles_article: Have you been annotated?
    DB_articles_article -->> Annotator : No
    Annotator->>DB_ontologies_ontology: Get the first label from ontologies
    DB_ontologies_ontology-->>Annotator: returns first label and its data
    loop Find this keyword
       Annotator ->> DB_articles_article: find_keyword(label)
       DB_articles_article -->> Annotator:  found
       Note over Annotator: change article and create annotation.
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```

**Comment by hasangokce** [comment]
Search performance before search indexes:

![image](https://user-images.githubusercontent.com/25805267/103168586-80749780-4845-11eb-9307-2b8867b28dc2.png)

**Comment by hasangokce** [comment]
```mermaid
sequenceDiagram
    participant Annotator
    participant DB_articles_article
    participant DB_ontologies_ontology
    participant Annotation
    Annotator ->> DB_articles_article: Have you been annotated?
    DB_articles_article -->> Annotator : No
    Annotator->>DB_ontologies_ontology: Get the first label from ontologies
    DB_ontologies_ontology-->>Annotator: returns first label and its data
    loop Find this keyword
       Annotator ->> DB_articles_article: find_keyword(label)
       DB_articles_article -->> Annotator:  found
    end
    Note right of DB_ontologies_ontology:  change article<br/>and <br/>create annotation.!
```

**Comment by hasangokce** [comment]
```mermaid
sequenceDiagram
    participant Annotator
    participant DB_articles_article
    participant DB_ontologies_ontology
    participant Annotation
    Note right of DB_articles_article:  change article<br/>and <br/>create annotation.!
    Annotator ->> DB_articles_article: Have you been annotated?
    DB_articles_article -->> Annotator : No
    Annotator->>DB_ontologies_ontology: Get the first label from ontologies
    DB_ontologies_ontology-->>Annotator: returns first label and its data
    Annotator ->> DB_articles_article: find_keyword(label)
    DB_articles_article -->> Annotator:  found
    Annotator ->> Annotator: create_target(source, type, value) 
    opt Body is not required
    Annotator ->> Annotator: create_body(type, value, format, language)
    Annotator ->> Annotator: create_annotation(target, body)
    end
    Annotator ->> Annotator: create_annotation(target)
    Annotator ->> DB_annotations_annotation: save_annotation(json_ld)
    DB_annotations_annotation -->> Annotator: annotation has been saved as json-ld

```

**Comment by hasangokce** [comment]
```mermaid
sequenceDiagram
    participant Annotator
    participant DB_articles_article
    participant DB_ontologies_ontology
    participant Annotation
    Note right of DB_articles_article:  change article<br/>and <br/>create annotation.!
    Annotator ->> DB_articles_article: Have you been annotated?
    DB_articles_article -->> Annotator : No
    Annotator->>DB_ontologies_ontology: Get the first label from ontologies
    loop Labels Loop
    DB_ontologies_ontology-->>Annotator: returns first label and its data
    Annotator ->> DB_articles_article: find_keyword(label)
    loop Keyword Loop
    DB_articles_article -->> Annotator:  found
    Annotator ->> Annotator: create_target(source, type, value) 
    opt Body is not required
    Annotator ->> Annotator: create_body(type, value, format, language)
    Annotator ->> Annotator: create_annotation(target, body)
    end
    Annotator ->> Annotator: create_annotation(target)
    Annotator ->> Annotation: save_annotation(json_ld)
    Annotation ->> DB_annotations_annotation: save()
    
    DB_annotations_annotation -->> Annotation: saved
    Annotation -->> Annotator: annotation has been saved as json-ld
    end
    end

```

**Comment by hasangokce** [comment]
```mermaid
sequenceDiagram
    participant Annotator
    participant DB_articles_article
    participant DB_ontologies_ontology
    participant Annotation

    Note left of Annotator:  find labels on articles<br/>* create annotations<br/>* update abstract
    Annotator ->> DB_articles_article: Have you been annotated?
    DB_articles_article -->> Annotator : No
    Annotator->>DB_ontologies_ontology: Get labels from ontologies
    DB_ontologies_ontology -->> Annotator: returns a list including labels
    
    Annotator->>Annotator: Start loop for labels
    loop label in labels
    Annotator->>DB_ontologies_ontology: Get the label's data from ontologies
    DB_ontologies_ontology-->>Annotator: returns label and its data
    Annotator ->> DB_articles_article: find_keyword(label)
    DB_articles_article -->> Annotator:  found positions

    Annotator->>Annotator: Start loop for positions
    loop Replace Loop
    Annotator ->> Annotator: create_target(source, type, value) 
    opt if it has a body
    Annotator ->> Annotator: create_body(type, value, format, language)
    Annotator ->> Annotator: create_annotation(target, body)
    end
    Annotator ->> Annotator: create_annotation(target)
    Annotator ->> Annotation: save_annotation(json_ld)
    Annotation ->> DB_annotations_annotation: save()
    DB_annotations_annotation -->> Annotation: saved
    Annotation -->> Annotator: annotation has been saved as json-ld
    Annotator ->> DB_articles_article: update_abstract(keyword, position)
    DB_articles_article -->> Annotator: article's abstract updated.
    end
    end

```

**Comment by hasangokce** [comment]
**Before:**
Recently, endemic novel coronavirus is an endemic global issue and having a negative
impact on the economy of the whole world. Like other countries, it also effected the economy and people of Pakistan. According to the publicly reported
data, the first case of novel corona virus in Pakistan was reported on 27th
February 2020. The aim of the present study is to describe the mathematical
model and dynamics of COVID-19 in Pakistan. To investigate the spread of coronavirus in Pakistan, we develop the SEIR time fractional model with newly,
developed fractional operator of Atangana-Baleanu. We present briefly the analysis of the given model and discuss its applications using world health organization (WHO) reported data for Pakistan. We consider the available infection cases from 19th March 2020, till 31st March 2020 and accordingly, various parameters are fitted or estimated. It is worth noting that we have calculated the basic reproduction number [Formula: see text] which shows that virus is spreading rapidly. Furthermore, stability analysis of the model at disease free equilibrium DFE and endemic equilibriums EE is performed to observe the dynamics and transmission of the model. Finally, the AB fractional model is solved numerically. To show the effect of the various embedded parameters like fractional parameter [Formula: see text] on the model, various graphs are plotted. It is worth noting that the base of our investigation, we have predicted basic reproduction number the spread of disease for next 200 days a endemic.

**After:**

Recently, <div id="covid19-c1bcf7a1-699e-482e-a103-939deaf65228">endemic</div> novel coronavirus is an <div id="covid19-c80b6f43-384e-476b-8837-02aeae3d2848">endemic</div> global issue and having a negative
impact on the economy of the whole world. Like other countries, it also effected the economy and people
of Pakistan. According to the publicly reported
data, the first case of novel corona virus in Pakistan was reported on 27th
February 2020. The aim of the present study is to describe the mathematical
model and dynamics of <div id="covid19-1bb9979e-de7b-4bb9-87a8-68e5193245e4">COVID-19</div> in Pakistan. To investigate the spread of coronavirus in Pakistan, we develop the SEIR time fractional model with newly,
developed fractional operator of Atangana-Baleanu. We present briefly the analysis of the given model and discuss its applications using world health <div id="covid19-a5036d77-6935-43c5-ae9e-f7f338d5af7a">organ</div>ization (WHO) reported data for Pakistan. We consider the available infection cases from 19th March 2020, till 31st March 2020 and accordingly, various parameters are fitted or estimated. It is worth
noting that we have calculated the <div id="covid19-b5944900-d5d7-44bd-8f5d-5f380acecba6">basic <div id="covid19-3f0156a4-1e5f-4ea4-9585-60ff4f531fc1">reproduction number</div></div> [Formula: see text] which shows that virus is spreading rapidly. Furthermore, stability analysis of the model at <div id="covid19-59e6f16d-16c0-45d2-8ccf-b1c98c4abf83">disease</div> free equilibrium DFE and <div id="covid19-9b1e325c-957e-4c46-a147-6ce3b578a0b1">endemic</div> equilibriums EE is performed to observe the dynamics and transmission of the model. Finally, the AB fractional model is solved numerically. To show the effect of the various embedded parameters like fractional parameter [Formula: see text] on the model, various graphs
are plotted. It is worth noting that the base of our investigation, we have predicted <div id="covid19-db82df31-da6f-497d-b803-7b4a443e4f71">basic <div id="covid19-81095a9c-99ac-44b7-8436-8fad9e77663d">reproduction number</div></div> the spread of <div id="covid19-fe7836a4-25de-48f0-b6ad-d5289b9c2e7b">disease</div> for next 200 days a <div id="covid19-e8152949-6d9d-4954-ba24-5fcabf924378">endemic</div>.

**Comment by hasangokce** [comment]
`health <div id="covid19-a5036d77-6935-43c5-ae9e-f7f338d5af7a">organ</div>ization`

```
we have predicted 
<div id="covid19-db82df31-da6f-497d-b803-7b4a443e4f71">
basic <div id="covid19-81095a9c-99ac-44b7-8436-8fad9e77663d">reproduction number</div></div>
the spread of
```

**Comment by hasangokce** [comment]
```
// changes all occurences with new keyword/
word = 'endemic'
new_word = '<div id="covid19-bec2cf0c-0312-46cc-bff1-307ac351b04b">endemic</div>'

i = 0
while( i <= len(sample)):
    print('start while')
    index = sample.find(word, i)

    if index != -1:
        i = i + index + len(new_word)
        second_start = len(word) + index
        sample = sample[:index] + new_word + sample[second_start:]
    else:
        break
```
