### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by hasangokce** [HBilge/Dolphin#80]
## Tasks

- [x] complete faceted search @kaksoy 
- [x] integrate basic search with dimensional search @HBilge @kaksoy 
- [x] use comma instead of space @HBilge @kaksoy 
- [x] lack of combinations for dimensions @HBilge 
- [x] print query term to the screen @kaksoy 
- [x] detail page annotation @hasangokce 
- [x] create annotations for 86000 articles @hasangokce 
- [x] get ifs from synonymouses and children from `ontologies.ontology` and `annotations.annotation` @kaksoy @HBilge 
- [x] daily updates for new articles and their annotations @kaksoy @hasangokce @HBilge 
- [x] convert `left amygdala ` to `left and right amygdala` expect two additional words in between @kaksoy 
- [x] and, or,... ignore these words @kaksoy 

## Reports related to-dos:

- [x] explain the situation for ontologies update
- [x] batch process detail for article and annotations update
- [x] add standard and versions that you use

## Documentation related tasks
- [x] Update class diagrams
- [x] Update sequence diagrams
- [x] Documentation will be completed

**Comment by hasangokce** [comment]
Reports related to dos:

- [ ] explain the situation for ontologies update
- [ ] batch process detail for article and annotations update
- [ ] add standard and versions that you use

**Comment by kaksoy** [comment]
use comma instead of space @kaksoy --> Updated and tested. Done.

![image](https://user-images.githubusercontent.com/61191703/104963138-8728a180-59e2-11eb-865a-9e2a44d4d8a4.png)

**Comment by kaksoy** [comment]
print query term to the screen @kaksoy --> Updated and tested. Done.

![image](https://user-images.githubusercontent.com/61191703/104964057-65c8b500-59e4-11eb-8464-8561f5caca96.png)

![image](https://user-images.githubusercontent.com/61191703/104964155-885ace00-59e4-11eb-98bf-c2b66ad2d2ec.png)

**Comment by kaksoy** [comment]
convert left amygdala to left and right amygdala expect two additional words in between@kaksoy --> Right query format is formed below, still working on the backend side to adjust this to our search:

To receive word1 and word2 as search keywords but also accepting 0-4 words in between during a search:
		
		(?i)\bword1\b\W+(?:\w+\W+){0,4}?\bword2\b

and, or,... ignore these words @kaksoy --> Right query format is formed below, still working on the backend side to adjust this to our search:
		
To ignore some undesired keywords from the search query:
		
		(?i)\b(?:(?!\bword1\b|\bword2\b|\bword3\b)\w)+\b

**Comment by kaksoy** [comment]
convert left amygdala to left and right amygdala hence expect two additional words in between@kaksoy --> Completed! There are from 0 to 4 words expected in between.

and, or,... ignore these words @kaksoy -->Completed. If there are "and",  "or", "but" in one search keyword then these words are ignored.

Below is a sample template of how search is done with updates above:

![image](https://user-images.githubusercontent.com/61191703/105038066-89810f00-5a67-11eb-97a5-509e3bc2b482.png)

![image](https://user-images.githubusercontent.com/61191703/105038135-9e5da280-5a67-11eb-9d4f-ee1972f6c6c6.png)

![image](https://user-images.githubusercontent.com/61191703/105038311-d533b880-5a67-11eb-8390-f22435f0033d.png)

**Comment by kaksoy** [comment]
Faceted search based on date and author's location has been added:

articles.html:

![image](https://user-images.githubusercontent.com/61191703/106295241-db404b00-6258-11eb-93e0-22380201659b.png)

/articles/views.py:

![image](https://user-images.githubusercontent.com/61191703/106295387-0aef5300-6259-11eb-9733-cee05efb6a46.png)
